seem.seem_display.*:
  type: config_entity
  label: 'Seem display config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    plugin:
      type: string
    context:
      type: sequence
      sequence:
        - type: string
    parameters:
      type: sequence
      sequence:
        - type: string
    config:
      type: sequence
      label: 'Config'
      sequence:
        - type: string